# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ad test
email: newthing42@hotmail.com
description: > 
  Gonna Advertise here now
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shadowjames42.github.io/" # the base hostname & protocol for your site
#twitter_username: Shadowjames42
#github_username:  Shadowjames42

# Build settings
markdown: kramdown
